### ISSUE TITLE
kubectl exec env error

### ISSUE THREAD

**Issue by spkane** [sethp-nr/guestbook-workshop#1]
@sethp-nr 

When running `kubectl exec $(kubectl get po -l app=guestbook -o name | head -n1) env`, I get the error `error: invalid resource name "pod/frontend-678d98b8f7-46p2r": [may not contain '/']`

I had to modify the command to this:

`k exec $(k get po -l app=guestbook -o name | head -n1 | cut -f 2 -d '/') env`

**Comment by sethp-nr** [comment]
I think that's something that changed with kubectl 1.15 – when we looked at your envionment, the kubectl you were using was the v1.14 that shipped with `kubebuilder`.

I like your `cut` idea though! That's a good option if kubectl 1.15 is not possible.
